---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrations-poc
spec:
  selector:
    matchLabels:
      app: integrations-poc
  template:
    metadata:
      labels:
        app: integrations-poc
    spec:
      containers:
        - name: api
          image: gcr.io/experiments-283423/lucastamoios/integrations:<VERSION>
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: integrations-poc
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: integrations-poc
                  key: client-secret
            - name: GIN_MODE
              value: release
            - name: POSTGRES_CONN
              value: dbname=toggl_integrations host=integrations-poc-postgres sslmode=disable user=postgres
          ports:
            - containerPort: 8080
